# Generated by Django 4.2.6 on 2023-12-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('created_at',)},
        ),
    ]
