# Generated by Django 4.2.6 on 2023-12-29 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationmessage',
            options={'ordering': ('created_at',)},
        ),
    ]
